### ISSUE TITLE
Unexpected behaviours of the download feature

### ISSUE THREAD

**Issue by paul-breen** [geodesystems/ramadda#4]
We have recently updated our version of Ramadda, and have found what appears to be a regression.

The primary problem for us, is that the download feature doesn't work as it did in our previous version.  There are three related aspects to this, but they're all related to the download feature.  Let me know if you'd rather these were raised as three separate issues.  I'd be happy to do so.

Our usage of Ramadda is basic.  We use it as a [download service](https://ramadda.data.bas.ac.uk/repository/), that exposes the files that make up the published datasets in our data centre ([UK Polar Data Centre](https://www.bas.ac.uk/data/uk-pdc/)).

We updated our previous version of Rammada (2.2) to the latest version at the time we started the project (12.9.0).

Note that all of our dataset entries in Ramadda are `Server Side Files`.  I believe this is significant in the problems that we're seeing.

We've identified these three problems, in order of severity, with regards to downloading a dataset:

1. When using the `Zip and Download Tree` feature, the resultant zipfile flattens the dataset directory structure.  This removes important (sometimes critical) metadata of the dataset, for example, if subdirectories are named as dates.  It also means that files that have the same name but are in different subdirectories get renamed with arbitrary leading digits (e.g., 1_, 2_1 etc.).  This is a significant problem for us, as it arbitrarily changes the resultant dataset.  Most of these datasets have a DOI, and flattening them in this manner means that they may contradict the corresponding published metadata record in our [catalogue](https://data.bas.ac.uk/).

1. When selecting `Zip and Download Tree` from the table entry form and clicking the `All` button, only files in the top-level directory are included in the resultant zipfile.  I think this is incorrect behaviour.  When selecting `Zip and Download Tree` from the table entry form, checking the `Toggle all` checkbox, and clicking the `Selected` button, only those files that are *visible* in the table are actually checked and subsequently included in the zipfile.  Files in non-expanded subdirectories are not checked and not included in the zipfile.  However, if expanding a subdirectory, and then re-toggling the `Toggle all` checkbox, the files in that subdirectory *are* then checked and included in the zipfile.  I think this is a bug.  Some of our datasets have hundreds of subdirectories, and these can be multiple levels deep.

1. The behaviour of the `Zip and Download Tree` option from the main entry menu is different to that of the same option in the table entry form.  Unfortunately, it too only downloads those files that are visible, but the resultant zipfile is named after the entry name, rather than `Results.zip`, as it is when using the option from the table entry form.  This isn't a major problem, but I think the differing behaviour is somewhat confusing.

In our previous version of Ramadda, downloading a dataset preserved the directory structure and included all files.  This is our desired behaviour.

I have also deployed the latest version of Ramadda 15.26.0 (at least as it was yesterday) to a development VM and can confirm that the above problems are still present.

I can also confirm that this isn't isolated to our deployment alone.  I note that NOAA too have `Server Side Files` exposed in a Ramadda instance (14.13.0), and that instance has these same behaviours.  For example: https://psl.noaa.gov/repository/entry/show?entryid=synth%3Ae570c8f9-ec09-4e89-93b4-babd5651e7a9%3AL3ByZWNs.

**Comment by jeffmcwhirter** [comment]
Hi Paul,
Sorry you had a problem. I believe sometime last year I made a change to
exclude the synthetic entries (i.e., those that aren't in the database like
the server side files) from the Zip and Download Tree output. I don't
recall exactly why but I think it had something to do with the AWS/S3
integration I implemented.

I changed that behavior so now the entire tree of files will get zipped up.
Here is a test on ramadda.org -
https://ramadda.org/repository/entry/show?entryid=882ba673-72b0-4d26-80de-e10f34721d72

This results in a zip with a directory and file structure that mimics the
entry hierarchy in RAMADDA

I have made a new release and it is available at-
https://ramadda.org/repository/alias/release

As to the different names for the zip file - the menu based "Zip and
Download..." command knows what is the source parent entry and uses that
for the name. However, the table based selection as well as the search
results based Zip & Download doesn't really know about the source parent
entry and thus uses the name Results.zip.

-Jeff

**Comment by paul-breen** [comment]
Hi Jeff,

That's great, thanks!  That test is exactly what we want.  I'll grab the new release and see if we can get it deployed to production.

And thanks for the explanation about the different names for the zip file.  That makes sense.  As I said, that isn't a biggie, but I thought I'd mention it, as it was related to the other issues.

Thanks,
Paul.

**Comment by paul-breen** [comment]
Hi Jeff,

Just to complete this issue.  We downloaded that release and have deployed it to our production server.  I can confirm that the issue is now fixed.  Thanks very much.
